INSERT INTO "Plants" ("NameRu", "NameLatin", "HeightMax", "GrowthRate", "Lifespan")
VALUES
    ('Актинидия коломикта', 'Actinidia kolomikta', 6, 0.2, 30),
    ('Аристолохия маньчжурская', 'Aristolochia manshuriensis', 3, 0.15, 20),
    ('Виноград амурский', 'Vitis amurensis', 8, 0.32, 25),
    ('Девичий виноград пятилисточковый', 'Parthenocissus quinquefolia', 15, 0.3, 50),
    ('Древогубец лазящий', 'Clematis vitalba', 12, 0.48, 25),
    ('Древогубец плетеобразный', 'Clematis terniflora', 10, 0.5, 20),
    ('Жимолость каприфоль', 'Lonicera caprifolium', 6, 0.24, 25),
    ('Клематис тангутский', 'Clematis tangutica', 3, 0.2, 15),
    ('Княжик сибирский', 'Corydalis sibirica', 1.2, 0.24, 5),
    ('Лимонник китайский', 'Schisandra chinensis', 5, 0.1, 50),
    ('Луносемянник даурский', 'Cucumis dahuricus', 2, 0.667, 3),
    ('Паслен сладко-горький', 'Solanum dulcamara', 3, 0.2, 15),
    ('Тладианта сомнительная', 'Thladiantha dubia', 3, 0.6, 5),
    ('Трехкрыльник Регеля', 'Tripterygium regelii', 4, 0.2, 20),
    ('Хмель обыкновенный', 'Humulus lupulus', 7, 0.35, 20),
    ('Помидорное дерево', 'Solanum betaceum', 5, 0.5, 10),
    ('Томат индетерминантный', 'Solanum lycopersicum', 2, 2.0, 1),
    ('Тыква декоративная', 'Cucurbita pepo var. ovifera', 2, 2.0, 1),
    ('Тыква фиголистная', 'Cucurbita ficifolia', 3, 3.0, 1),
    ('Бешеный огурец', 'Ecballium elaterium', 1, 1.0, 1),
    ('Кабачок цукини', 'Cucurbita pepo var. cylindrica', 1.5, 1.5, 1),
    ('Патиссон', 'Cucurbita pepo var. patisonina', 1.5, 1.5, 1),
    ('Тыква мускатная', 'Cucurbita moschata', 3, 1.5, 2);